---
output: github_document
---

<!-- NEWS.md is generated from NEWS.Rmd. Please edit that file -->
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# contact 1.0.0 

* submitted to CRAN on 10/18/2019 

## contact 1.0.1

* Addressed issues highlighted from CRAN reviewer.
* Fixed a substantial bug in the "chisq" sub-function of contactTest.

## contact 1.2.0

* Corrected many bugs in package functions.
* Improved efficiency (e.g., run time, local memory usage, etc.) of package functions
* Ensured compatability with R 4.0.0.
* Updated package citation (because our paper was accepted for publication!)
* Broke contact::contactTest into multiple functions - contactTest is now defunct.

## contact 1.2.1

* Fixed a bug introduced in version 1.2.0, as required by CRAN

## contact 1.2.2
* Fixed bug associated with temporal sorting of data spanning multiple years.
* Improved efficiency temporal blocking functions.

## contact 1.2.3
* Fixed bug that forced times in tempAggregate output to begin at 00:00:00 on the first day in the data set.
* Added socialEdges function.

## contact 1.2.4
* Fixed various bugs
* Realized that the method the findDistThresh function was based on was faulty due to a mistake in the paper (Farthing et al. 2020). We updated the function to correctly do as intended and updated to function documentation to acknowledge the mistake.
* Drastically improved efficiency of the ntwrkEdges function.

## contact 1.2.5
* Restored old functionality of the findDistThresh function while maintaining the additional output added in the previous update.

## contact 1.2.6
* Updated syntax to ensure continued CRAN compliance.
* Fixed errors in the vignette.

## contact 1.2.7
* Fixed error in the contactTest functions that prevent examples from being run in development environments with last.warning logs locked.

## contact 1.2.8
* Replaced "assign("last.warning", NULL, envir = baseenv())" in contactCompare functions with "warn1 <- NULL" to prevent CRAN errors. (Note: This may lead to bugs in the future, but we have to do this this to make CRAN cooperate....) 


```